# For Development Only
version: '3.7'

services:
  app:
    image: node:16
    command: sh -c "npm i -g pnpm && pnpm i --unsafe-perm && pnpm prisma migrate reset && pnpm prisma db push && pnpm prisma seed && pnpm dev"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: postgres:10.12
    ports:
      # expose the port in case if only db needs to be started
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
